In [1]:
import numpy as np

# Numpy Arthmetic and Statistical Functions


* abs()
* sqrt()
* sign()
* exp()
* sort()

In [2]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])
print(y)

[-1.4  0.4 -3.2  2.5  3.4]


In [3]:
print(np.abs(y))

[1.4 0.4 3.2 2.5 3.4]


In [4]:
print(np.sqrt(y)) #절대값을 취해줘야함

[       nan 0.63245553        nan 1.58113883 1.84390889]


C:\Users\leedo\AppData\Local\Temp/ipykernel_37876/996839701.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(y))


In [5]:
print(np.sqrt(abs(y)))

[1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]


In [6]:
print(np.sign(y)) #부호

[-1.  1. -1.  1.  1.]


In [7]:
print(np.exp(y))

[ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]


In [9]:
print(np.sort(y))

[-3.2 -1.4  0.4  2.5  3.4]


In [10]:
print(y)

[-1.4  0.4 -3.2  2.5  3.4]


* add()
* subtract()
* multiply()
* divide()
* maximum()

In [28]:
x = np.arange(-2,3)
y = np.arange(-4,6,2)
print(x)
print(y)

[-2 -1  0  1  2]
[-4 -2  0  2  4]


In [29]:
print(np.add(x,y))

[-6 -3  0  3  6]


In [30]:
print(np.subtract(x,y))

[ 2  1  0 -1 -2]


In [31]:
print(np.multiply(x,y))

[8 2 0 2 8]


In [32]:
print(np.divide(x,y))

[0.5 0.5 nan 0.5 0.5]


C:\Users\leedo\AppData\Local\Temp/ipykernel_37876/2793363925.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.divide(x,y))


In [33]:
print(np.maximum(x,y))

[-2 -1  0  2  4]


* min()
* max()

In [35]:
y = np.random.randn(5)
print(y)

[-0.80007796 -0.76465753  0.446192    0.75482345  0.77854932]


In [38]:
print(np.max(y))

0.7785493173749486


In [39]:
print(np.min(y))

-0.8000779616535834


* sum()

In [46]:
print(np.sum(y))

0.4148292767311498


* mean()
 * mean/average

In [44]:
print(np.mean(y))

0.08296585534622995


* std()
    * standard deviation(표준편차)


In [45]:
print(np.std(y))

0.7162951900212876


* argwhere()
    * indexes satisfying condition
    * 조건을 만족시키는 인덱스

In [47]:
M = np.arange(25).reshape(5,5)
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [48]:
print(M[M%2==1])

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [49]:
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [54]:
print(np.argwhere(M>=20))

[[4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]


In [62]:
#홀수인 원소는 그대로, 짝수인 원소는 0으로 
print(np.where(M%2==1,M,0)) 

[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


# New axis
* 새로운 축 추가/ 차원 확대

In [66]:
t = np.array([1,2,3])
print(t.shape)

(3,)


In [71]:
x = t[np.newaxis, :]
print(x)
print(x.shape)

[[1 2 3]]
(1, 3)


In [72]:
y = t[:, np.newaxis]
print(y)
print(y.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [73]:
print(t)
print(x)
print(y)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]
